apiVersion: v1
kind: Pod
metadata:
  name: cel-bad-hostpath
  namespace: cel-lab
  labels:
    app.kubernetes.io/name: cel-bad-hostpath
    app.kubernetes.io/part-of: policy-lab
    owner: platform-security
    env: dev
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - name: host-etc
      hostPath:
        path: /etc
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      volumeMounts:
        - name: host-etc
          mountPath: /host-etc
          readOnly: true
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
