apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-good-deployment
  namespace: kyverno-lab
  labels:
    team: platform-security
    app: test-app
    cost-center: infra-001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: nginxinc/nginx-unprivileged:1.27
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
