apiVersion: v1
kind: Pod
metadata:
  name: good-kyverno-required-label
  namespace: policy-lab
  labels:
    training.kyverno.io/phase: "4"
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: nginxinc/nginx-unprivileged:1.27
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
