apiVersion: v1
kind: Pod
metadata:
  name: gatekeeper-privileged
  namespace: gatekeeper-lab
  labels:
    app.kubernetes.io/name: gatekeeper-privileged
    owner: platform-security
    env: dev
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: nginxinc/nginx-unprivileged:1.27
      securityContext:
        privileged: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
