apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sChallengeRequiredLabels
metadata:
  name: challenge-pods-must-have-labels
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - gatekeeper-lab
  parameters:
    labels:
      - app.kubernetes.io/name
      - owner
      - env
