apiVersion: v1
kind: Pod
metadata:
  name: kyverno-missing-security
  namespace: kyverno-lab
  labels:
    app.kubernetes.io/name: kyverno-missing-security
    owner: platform-security
    env: dev
spec:
  containers:
    - name: app
      image: nginxinc/nginx-unprivileged:1.27
      ports:
        - containerPort: 8080
