apiVersion: v1
kind: Pod
metadata:
  name: gatekeeper-good
  namespace: gatekeeper-lab
  labels:
    app.kubernetes.io/name: gatekeeper-good
    owner: platform-security
    env: dev
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: nginxinc/nginx-unprivileged:1.27
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
